In [1]:
# Import Bike Data Set
# Data source = http://archive.ics.uci.edu/ml/machine-learning-databases/00275/
# https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset
# https://archive.ics.uci.edu/ml/datasets.html?format=&task=reg&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
names = ['instant','dteday','season','yr','mnth','holiday','weekday','workingday','weathersit','temp','atemp,','hum',
         'windspeed','casual','registered','cnt']
bike  = pd.read_csv("C:/Users/boyerm/Documents/Thinkful/hour.csv",header = 1, names = names )

In [2]:
bike.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,"atemp,",hum,windspeed,casual,registered,cnt
2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1

In [3]:
bike.describe()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,"atemp,",hum,windspeed,casual,registered,cnt
count,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000,17378.00000,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000,17378.000000
mean,2.501726,0.502589,6.538094,11.547416,0.028772,3.00351,0.682760,1.425308,0.497002,0.475786,0.627218,0.190109,35.678099,153.794971,189.473069
std,1.106891,0.500008,3.438618,6.914049,0.167170,2.00570,0.465415,0.639367,0.192552,0.171849,0.192930,0.122335,49.305826,151.357873,181.388045
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,4.000000,6.000000,0.000000,1.00000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,3.000000,1.000000,7.000000,12.000000,0.000000,3.00000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,3.000000,1.000000,10.000000,18.000000,0.000000,5.00000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,4.000000,1.000000,12.000000,23.000000,1.000000,6.00000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor


rfc = ensemble.RandomForestRegressor()
X = bike.drop('registered', 1)
X = bike.drop('instant',1)
Y = bike['registered']
X = pd.get_dummies(X)

cross_val_score(rfc, X, Y, cv=5)

array([ 0.99999993,  0.9999995 ,  0.99999959,  0.99999303,  0.9994488 ])

In [ ]:
 # can't do the decision tree because the packages won't load.